import '@/styles/globals.css';
import { AddressBar } from '@/ui/address-bar';
//import './globals.css'
import Byline from '@/ui/byline';
import { GlobalNav } from '@/ui/global-nav'
import Sidebar from '@/ui/sidebar';
import SidebarProvider from '@/context/sidebar-context';
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="[color-scheme:dark]">
      <body className="bg-gray-1100 overflow-y-scroll bg-[url('/grid.svg')] pb-36">
      <SidebarProvider>
      <Sidebar />
        <div className="lg:pl-72">
          <div className="mx-auto max-w-4xl space-y-8 px-2 pt-20 lg:py-8 lg:px-8">
            <div className="rounded-lg bg-vc-border-gradient p-px shadow-lg shadow-black/20">
            </div>

            <div className="rounded-lg bg-vc-border-gradient p-px shadow-lg shadow-black/20">

              <div className="rounded-lg bg-black p-3.5 lg:p-6">{children}</div>
        
            </div>
            <Byline className="fixed sm:hidden" />
          </div>
        </div>
        </SidebarProvider>
      </body>
    </html>
  )
}
